{
 "title": "multi-region v2",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "table",
    "label": "Table Ranges",
    "query": "rides, users, vehicle_location_histories, vehicles"
   },
   { "name": "region", "label": "Region (for cluster info)", "query": "westus2, eastus2, centralus" }
  ]
 },
 "panels": [
  { "title": "Range Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Ranges for table \"${table}\"",
   "type": "table",
   "gridPos": { "h": 8, "w": 23, "x": 0, "y": 1 },
   "targets": [
    {
     "rawSql": "select range_id, lease_holder, lease_holder_locality, voting_replicas, non_voting_replicas from [show ranges from table ${table} with details];"
    }
   ]
  },
  { "title": "Cluster Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Node Information",
   "type": "table",
   "gridPos": { "h": 7, "w": 23, "x": 0, "y": 10 },
   "targets": [
    {
     "rawSql": "select node_id as node, address, locality, server_version as version, is_live as \"is live\", ranges, leases, started_at as \"started at\"\r\nfrom crdb_internal.gossip_nodes\r\nwhere locality ~ '${region:regex}'\r\norder by locality"
    }
   ]
  },
  {
   "title": "Cluster Locations",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Cluster Location",
     "type": "geomap",
     "description": "Cluster Regions",
     "gridPos": { "h": 6, "w": 23, "x": 0, "y": 16 },
     "targets": [
      {
       "rawSql": "with regions as (\r\n  SELECT row_number() OVER (), *\r\n  FROM (\r\n      select latitude, longitude, \"localityValue\" \r\n      from system.locations \r\n      where \"localityValue\" in (select region from [show regions])\r\n        )\r\n)\r\nselect * from regions"
      },
      {
       "rawSql": "with regions as (\r\n  SELECT row_number() OVER (), *\r\n  FROM (\r\n      select latitude, longitude, \"localityValue\" \r\n      from system.locations \r\n      where \"localityValue\" in (select region from [show regions])\r\n        )\r\n)\r\nselect * from regions where row_number in (1,2)"
      },
      {
       "rawSql": "with regions as (\r\n  SELECT row_number() OVER (), *\r\n  FROM (\r\n      select latitude, longitude, \"localityValue\" \r\n      from system.locations \r\n      where \"localityValue\" in (select region from [show regions])\r\n        )\r\n)\r\nselect * from regions where row_number in (1,3)"
      },
      {
       "rawSql": "with regions as (\r\n  SELECT row_number() OVER (), *\r\n  FROM (\r\n      select latitude, longitude, \"localityValue\" \r\n      from system.locations \r\n      where \"localityValue\" in (select region from [show regions])\r\n        )\r\n)\r\nselect * from regions where row_number in (2,3)"
      }
     ]
    }
   ]
  },
  {
   "title": "Global Tables (users, vehicles)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "Reads",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "targets": [
      {
       "expr": "rate(read_user_latency_sum[5m])/rate(read_user_latency_count[5m])",
       "legendFormat": "westus2"
      },
      {
       "expr": "rate(read_user_latency_sum[5m])/rate(read_user_latency_count[5m])",
       "legendFormat": "centralus"
      },
      {
       "expr": "rate(read_user_latency_sum[5m])/rate(read_user_latency_count[5m])",
       "legendFormat": "eastus2"
      }
     ]
    },
    {
     "title": "Writes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
     "targets": [
      {
       "expr": "rate(update_vehicle_status_latency_sum[5m])/rate(update_vehicle_status_latency_count[5m])",
       "legendFormat": "westus2"
      },
      {
       "expr": "rate(update_vehicle_status_latency_sum[5m])/rate(update_vehicle_status_latency_count[5m])",
       "legendFormat": "centralus"
      },
      {
       "expr": "rate(update_vehicle_status_latency_sum[5m])/rate(update_vehicle_status_latency_count[5m])",
       "legendFormat": "eastus2"
      }
     ]
    }
   ]
  },
  { "title": "Regional Tables (rides)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Reads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "rate(read_a_ride_summary_latency_sum[5m])/rate(read_a_ride_summary_latency_count[5m])",
     "legendFormat": "westus2"
    },
    {
     "expr": "rate(read_a_ride_summary_latency_sum[5m])/rate(read_a_ride_summary_latency_count[5m])",
     "legendFormat": "centralus"
    },
    {
     "expr": "rate(read_a_ride_summary_latency_sum[5m])/rate(read_a_ride_summary_latency_count[5m])",
     "legendFormat": "eastus2"
    }
   ]
  },
  {
   "title": "AOST Reads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 20 },
   "targets": [
    {
     "expr": "rate(read_a_ride_summary_aost_latency_sum[5m])/rate(read_a_ride_summary_aost_latency_count[5m])",
     "legendFormat": "westus2"
    },
    {
     "expr": "rate(read_a_ride_summary_aost_latency_sum[5m])/rate(read_a_ride_summary_aost_latency_count[5m])",
     "legendFormat": "centralus"
    },
    {
     "expr": "rate(read_a_ride_summary_aost_latency_sum[5m])/rate(read_a_ride_summary_aost_latency_count[5m])",
     "legendFormat": "eastus2"
    }
   ]
  },
  {
   "title": "Writes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 20 },
   "targets": [
    {
     "expr": "rate(add_a_ride_latency_sum[5m])/rate(add_a_ride_latency_count[5m])",
     "legendFormat": "westus2"
    },
    {
     "expr": "rate(add_a_ride_latency_sum[5m])/rate(add_a_ride_latency_count[5m])",
     "legendFormat": "centralus"
    },
    {
     "expr": "rate(add_a_ride_latency_sum[5m])/rate(add_a_ride_latency_count[5m])",
     "legendFormat": "eastus2"
    }
   ]
  },
  {
   "title": "Regional By Row Tables (vehicle_location_histories)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "title": "Reads",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
     "targets": [
      {
       "expr": "rate(read_vehicle_location_latency_sum[5m])/rate(read_vehicle_location_latency_count[5m])",
       "legendFormat": "westus2"
      },
      {
       "expr": "rate(read_vehicle_location_latency_sum[5m])/rate(read_vehicle_location_latency_count[5m])",
       "legendFormat": "centralus"
      },
      {
       "expr": "rate(read_vehicle_location_latency_sum[5m])/rate(read_vehicle_location_latency_count[5m])",
       "legendFormat": "eastus2"
      }
     ]
    },
    {
     "title": "Writes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
     "targets": [
      {
       "expr": "rate(update_vehicle_location_latency_sum[5m])/rate(update_vehicle_location_latency_count[5m]) ",
       "legendFormat": "westus2"
      },
      {
       "expr": "rate(update_vehicle_location_latency_sum[5m])/rate(update_vehicle_location_latency_count[5m]) ",
       "legendFormat": "centralus"
      },
      {
       "expr": "rate(update_vehicle_location_latency_sum[5m])/rate(update_vehicle_location_latency_count[5m]) ",
       "legendFormat": "eastus2"
      }
     ]
    }
   ]
  }
 ]
}